### ISSUE TITLE
Where is installed and how to uninstall it

### ISSUE THREAD

**Issue by Aierbote** [TheJoeFin/Caffeinated#28]
_First thing first I don't know what caused some weird problems on my windows, I cannot even be sure if the fault was this app I installed from Microsoft Store, I just had to uninstall temporary, being one of the last installed applications._ 

I think it would beneficial to know where this app gets installed (maybe a small section on the `README.md` with even manual/automatic install) and a small section on how to uninstall it or even a small note on this utility settings.

I personally found it weird it was impossible to uninstall it from the good old _Control Pannel_ of Windows . I finally succeeded from `System Settings` -> `App` -> `Installed Apps` -> search for `Caffeinated` -> `Uninstall`

**Comment by TheJoeFin** [comment]
The app is installed as a packaged store app. To uninstall find "Caffeinated" in your Start menu list of all apps, right click, click uninstall. Or go system settings like you recommended.

Because this is a packaged app there is no recommended way to "manually uninstall" this app. The benefits of it being a packaged app is how self contained it is and does not put files in different spots like old Windows installers could and would.

**Comment by Aierbote** [comment]
Niiice, that's shorter solution, the more you know!

Thanks for the immediate answer, do you mind to add this small info on the `README.md`, please?
