### ISSUE TITLE
Consider more distinct icon

### ISSUE THREAD

**Issue by willnorris** [TheJoeFin/Caffeinated#9]
One of the difficulties I had with the original Caffeinated icon was that there wasn't sufficient visual distinction between the active and inactive state.  I actually have find the same to be true with your updated eye icon... I have to focus very carefully to tell the difference.

What would you think of using the Material filled and outline coffee cup icons, like @adriancampos did in https://github.com/adriancampos/Caffeinated/commit/02405bd9646bbe9566a6e23756a4ede1657a3a6c ?  I think it matches the Windows 10 system icons nicely, and is easy to tell the difference between the two.

**Comment by TheJoeFin** [comment]
I do like this idea. I might look into adding the option for people to pick between a few different options.

**Comment by TheJoeFin** [comment]
Here is one option I've made to make state more clear. Thoughts?

![NewIcons](https://user-images.githubusercontent.com/7809853/98055055-300f2980-1e02-11eb-82f4-246c4519d2e2.png)

**Comment by willnorris** [comment]
I generally find the eye icon less clear, both the existing and this new one.  Maybe that's just me?

But the coffee cup icon here is definitely clearer!  Though when empty, it's slightly less obvious what it is, compared to the Material icons.  But that's pretty minor.

**Comment by TheJoeFin** [comment]
Continuing to iterate on both designs:
![New Mug Icons](https://user-images.githubusercontent.com/7809853/98970686-d5e32800-24d5-11eb-8a31-fd2eaa6a5202.png)
![New Eye Icons](https://user-images.githubusercontent.com/7809853/98970692-d7aceb80-24d5-11eb-9e7d-cee3868ad39c.png)
![New Icons In Taskbar](https://user-images.githubusercontent.com/7809853/98970712-dd0a3600-24d5-11eb-98ec-5c3a7f555c93.png)

Mug is more obvious, but would change the identity of the app. The Eye more closely tracks with the original inspiration from Mac.

Am I overthinking people being confused with a different icon? Is the eye distinct enough? Since this is a systray app basically the entire UI is the icon, so I think getting it right is important.

**Comment by willnorris** [comment]
I don't think you're overthinking it at all, for exactly the reasons you mention!  This is the entire UI, so it's worth being really thoughtful about.

I'm curious to hear more about the eye tracking original inspiration from Mac.  I know these types of apps have been around for a while, and I honestly don't even know what the original is! :) I currently use [KeepingYouAwake](https://keepingyouawake.app/) on mac, which also uses a mug icon.

I actually think they eye metaphor of being open and closed works really well... it's obvious that an open eye keeps the machine awake.  My main concern was that the closed state icon was hard to tell what it really is at 16px (or whatever the icon size is).  In this latest example, I wouldn't intuitively know which state meant "stay awake" versus "allow sleep".  In fact, it's curious that it's the inverse of the mug icon?  Is that intentional?

I find the mug icon easy to distinguish visually, and I think(?) is intuitive as to which icon indicates which state, especially since it matches the system battery icon pretty well.

**Comment by TheJoeFin** [comment]
The current plan is to let users choose which icon they want to use. Here are the options.

![image](https://user-images.githubusercontent.com/7809853/99888555-670f7880-2c13-11eb-99c7-5bafeda767bb.png)

This is currently working for me and will soon be released.
